In [1]:
# Import module/s
import pandas as pd
import numpy as np

# File to Clean MVP2 Data

## NFL Cleaning
### NFL Team Value Data

In [2]:
# Load in NFL team valuation csv
nfl_team_val_file = '../data/raw/MVP2/nfl_team_valuation.csv'
nfl_team_val_data = pd.read_csv(nfl_team_val_file)

# Create DataFrame
nfl_team_val_df = pd.DataFrame(nfl_team_val_data)
nfl_team_val_df.head()

                   Team  2023 Franchise Value ($USD billions)
0        Dallas Cowboys                                   9.0
1  New England Patriots                                   7.0
2      Los Angeles Rams                                   6.9
3       New York Giants                                   6.8
4         Chicago Bears                                   6.3

In [3]:
# Analyze DF characteristics & info
nfl_team_val_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Team                                  32 non-null     object
 1   2023 Franchise Value ($USD billions)  32 non-null     float64
dtypes: float64(1), object(1)
memory usage: 640.0+ bytes

### NFL Revenue Data

In [23]:
# Load in NFL team & league revenue csv
nfl_revenue_file = '../data/raw/MVP2/nfl_league_team_revenue.csv'
nfl_revenue_data = pd.read_csv(nfl_revenue_file)

# Create DataFrame
nfl_revenue_df = pd.DataFrame(nfl_revenue_data)
nfl_revenue_df.head()

   Year NFL Revenue (USD Millions)
0  2022                      1,880
1  2021                      1,800
2  2020                      1,620
3  2019                      1,470
4  2018                      1,390

In [24]:
# Analyze DF characteristics & info
nfl_revenue_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        13 non-null     int64
 1   NFL Revenue (USD Millions)  13 non-null     object
dtypes: int64(1), object(1)
memory usage: 336.0+ bytes

**Cleaning Notes ^**
- Revenue column:
    - commas will need to changed to decimals 
    - Revenue numbers will need to be rounded to 1 decimal place to match billions format
    - Revenue column data type will need to be changed to float (decimal number)
    - Finally, rename column to billions for value

In [25]:
# Convert data type of revenue column to float
nfl_revenue_df['NFL Revenue (USD Millions)'] = nfl_revenue_df['NFL Revenue (USD Millions)'].str.replace(',', '.', regex=False).astype(float)

# Check success of replace
nfl_revenue_df.head()

   Year  NFL Revenue (USD Millions)
0  2022                        1.88
1  2021                        1.80
2  2020                        1.62
3  2019                        1.47
4  2018                        1.39

In [26]:
# Round Revenue column to 1 decimal place
nfl_revenue_df['NFL Revenue (USD Millions)'] = nfl_revenue_df['NFL Revenue (USD Millions)'].round(1)

# Check rounding
nfl_revenue_df.head()

   Year  NFL Revenue (USD Millions)
0  2022                         1.9
1  2021                         1.8
2  2020                         1.6
3  2019                         1.5
4  2018                         1.4

In [27]:
# Rename revenue column 
nfl_revenue_df = nfl_revenue_df.rename(columns={'NFL Revenue (USD Millions)':'NFL Revenue ($USD billions)'})

# Verify change
nfl_revenue_df.head()

   Year  NFL Revenue ($USD billions)
0  2022                          1.9
1  2021                          1.8
2  2020                          1.6
3  2019                          1.5
4  2018                          1.4