In [1]:
# Import module/s
import pandas as pd
import numpy as np

# File to Clean MVP2 Data

# NFL Cleaning
## NFL Team Value Data

In [2]:
# Load in NFL team valuation csv
nfl_team_val_file = '../data/raw/MVP2/nfl_team_valuation.csv'
nfl_team_val_data = pd.read_csv(nfl_team_val_file)

# Create DataFrame
nfl_team_val_df = pd.DataFrame(nfl_team_val_data)
nfl_team_val_df.head()

                   Team  2023 Franchise Value ($USD billions)
0        Dallas Cowboys                                   9.0
1  New England Patriots                                   7.0
2      Los Angeles Rams                                   6.9
3       New York Giants                                   6.8
4         Chicago Bears                                   6.3

In [3]:
# Analyze DF characteristics & info
nfl_team_val_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Team                                  32 non-null     object
 1   2023 Franchise Value ($USD billions)  32 non-null     float64
dtypes: float64(1), object(1)
memory usage: 640.0+ bytes

In [4]:
# Add NFL to column name for clarity
nfl_team_val_df = nfl_team_val_df.rename(columns={'2023 Franchise Value ($USD billions)':'2023 NFL Franchise Value (USD billions)'})

# Verify success
nfl_team_val_df.head()

                   Team  2023 NFL Franchise Value (USD billions)
0        Dallas Cowboys                                      9.0
1  New England Patriots                                      7.0
2      Los Angeles Rams                                      6.9
3       New York Giants                                      6.8
4         Chicago Bears                                      6.3

### NFL Revenue Data

In [5]:
# Load in NFL team & league revenue csv
nfl_revenue_file = '../data/raw/MVP2/nfl_league_team_revenue.csv'
nfl_revenue_data = pd.read_csv(nfl_revenue_file)

# Create DataFrame
nfl_revenue_df = pd.DataFrame(nfl_revenue_data)
nfl_revenue_df.head()

   Year NFL Revenue (USD Millions)
0  2022                      1,880
1  2021                      1,800
2  2020                      1,620
3  2019                      1,470
4  2018                      1,390

In [6]:
# Analyze DF characteristics & info
nfl_revenue_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        13 non-null     int64
 1   NFL Revenue (USD Millions)  13 non-null     object
dtypes: int64(1), object(1)
memory usage: 336.0+ bytes

**Cleaning Tasks Needed**
- Revenue column:
    - commas will need to changed to decimals 
    - Revenue numbers will need to be rounded to 1 decimal place to match billions format
    - Revenue column data type will need to be changed to float (decimal number)
    - Finally, rename column to billions for value

In [7]:
# Convert data type of revenue column to float
nfl_revenue_df['NFL Revenue (USD Millions)'] = nfl_revenue_df['NFL Revenue (USD Millions)'].str.replace(',', '.', regex=False).astype(float)

# Check success of replace
nfl_revenue_df.head()

   Year  NFL Revenue (USD Millions)
0  2022                        1.88
1  2021                        1.80
2  2020                        1.62
3  2019                        1.47
4  2018                        1.39

In [8]:
# Round Revenue column to 1 decimal place
nfl_revenue_df['NFL Revenue (USD Millions)'] = nfl_revenue_df['NFL Revenue (USD Millions)'].round(1)

# Check rounding
nfl_revenue_df.head()

   Year  NFL Revenue (USD Millions)
0  2022                         1.9
1  2021                         1.8
2  2020                         1.6
3  2019                         1.5
4  2018                         1.4

In [27]:
# Rename revenue column 
nfl_revenue_df = nfl_revenue_df.rename(columns={'NFL Revenue (USD Millions)':'NFL Revenue ($USD billions)'})

# Verify change
nfl_revenue_df.head()

   Year  NFL Revenue ($USD billions)
0  2022                          1.9
1  2021                          1.8
2  2020                          1.6
3  2019                          1.5
4  2018                          1.4

In [9]:
# Final DF info check
nfl_revenue_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        13 non-null     int64
 1   NFL Revenue (USD Millions)  13 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 336.0 bytes

# NBA Data Cleaning

## NBA Franchise Value Data

In [10]:
# Load in NBA franchise value csv
data = '../data/raw/MVP2/nba_franchise_values.csv'
nba_franchise_data = pd.read_csv(data)

# create DataFrame from data
nba_franchise_df = pd.DataFrame(nba_franchise_data)
# Show DF's first 5 rows
nba_franchise_df.head()

   Year Average NBA Franchise Value (USD Millions)
0  2023                                      3,850
1  2022                                    2,863.5
2  2021                                      2,480
3  2020                                      2,123
4  2019                                      1,868

In [11]:
# Review full DataFrame
nba_franchise_df

    Year Average NBA Franchise Value (USD Millions)
0   2023                                      3,850
1   2022                                    2,863.5
2   2021                                      2,480
3   2020                                      2,123
4   2019                                      1,868
5   2018                                    1,651.5
6   2017                                      1,355
7   2016                                      1,245
8   2015                                      1,106
9   2014                                        634
10  2013                                        509
11  2012                                        393
12  2011                                        369
13  2010                                        367
14  2009                                        379
15  2008                                        372
16  2007                                        353
17  2006                                        326
18  2005                                        302
19  2004                                        265
20  2003                                        248
21  2002                                        223
22  2001                                        207

In [12]:
# Check info on DataFrame
nba_franchise_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        23 non-null     int64
 1   Average NBA Franchise Value (USD Millions)  23 non-null     object
dtypes: int64(1), object(1)
memory usage: 496.0+ bytes

In [13]:
# Replace commas in franchise column with periods
nba_franchise_df['Average NBA Franchise Value (USD Millions)'] = nba_franchise_df['Average NBA Franchise Value (USD Millions)'].str.replace(',','.')

nba_franchise_df

    Year Average NBA Franchise Value (USD Millions)
0   2023                                      3.850
1   2022                                    2.863.5
2   2021                                      2.480
3   2020                                      2.123
4   2019                                      1.868
5   2018                                    1.651.5
6   2017                                      1.355
7   2016                                      1.245
8   2015                                      1.106
9   2014                                        634
10  2013                                        509
11  2012                                        393
12  2011                                        369
13  2010                                        367
14  2009                                        379
15  2008                                        372
16  2007                                        353
17  2006                                        326
18  2005                                        302
19  2004                                        265
20  2003                                        248
21  2002                                        223
22  2001                                        207

In [47]:
nba_franchise_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        23 non-null     int64
 1   Average NBA Franchise Value (USD Millions)  23 non-null     object
dtypes: int64(1), object(1)
memory usage: 496.0+ bytes

In [14]:
# Add decimal to far left of 2001-2014 values to show as parts of a billion (to match format in end)
def move_period_to_left(s):
    s = s.replace('.', '')  # Remove existing period
    return '.' + s  # Add period to the far left, "period + s(represents value)"

nba_franchise_df.loc[nba_franchise_df.index >= 9, 'Average NBA Franchise Value (USD Millions)'] = nba_franchise_df.loc[nba_franchise_df.index >= 9, 'Average NBA Franchise Value (USD Millions)'].apply(move_period_to_left)

nba_franchise_df

    Year Average NBA Franchise Value (USD Millions)
0   2023                                      3.850
1   2022                                    2.863.5
2   2021                                      2.480
3   2020                                      2.123
4   2019                                      1.868
5   2018                                    1.651.5
6   2017                                      1.355
7   2016                                      1.245
8   2015                                      1.106
9   2014                                       .634
10  2013                                       .509
11  2012                                       .393
12  2011                                       .369
13  2010                                       .367
14  2009                                       .379
15  2008                                       .372
16  2007                                       .353
17  2006                                       .326
18  2005                                       .302
19  2004                                       .265
20  2003                                       .248
21  2002                                       .223
22  2001                                       .207

In [15]:
# Function to remove incorrect second period (decimal)
def remove_period(s):
    parts = s.split('.')
    return '.'.join(parts[:2]) + ''.join(parts[2:])

nba_franchise_df['Average NBA Franchise Value (USD Millions)'] = nba_franchise_df['Average NBA Franchise Value (USD Millions)'].apply(remove_period)

nba_franchise_df

    Year Average NBA Franchise Value (USD Millions)
0   2023                                      3.850
1   2022                                     2.8635
2   2021                                      2.480
3   2020                                      2.123
4   2019                                      1.868
5   2018                                     1.6515
6   2017                                      1.355
7   2016                                      1.245
8   2015                                      1.106
9   2014                                       .634
10  2013                                       .509
11  2012                                       .393
12  2011                                       .369
13  2010                                       .367
14  2009                                       .379
15  2008                                       .372
16  2007                                       .353
17  2006                                       .326
18  2005                                       .302
19  2004                                       .265
20  2003                                       .248
21  2002                                       .223
22  2001                                       .207

In [16]:
# Convert franchise values to float then round to 1 decimal place
# 1) change type
nba_franchise_df['Average NBA Franchise Value (USD Millions)'] = nba_franchise_df['Average NBA Franchise Value (USD Millions)'].astype(float) 

# 2) round numbers over 1 billion to 1 place after decimal
nba_franchise_df.loc[nba_franchise_df.index < 9,'Average NBA Franchise Value (USD Millions)'] = nba_franchise_df.loc[nba_franchise_df.index < 9,'Average NBA Franchise Value (USD Millions)'].round(1)

# 3) round numbers less than 1 billion to 2 places after decimal
nba_franchise_df.loc[nba_franchise_df.index >= 9,'Average NBA Franchise Value (USD Millions)'] = nba_franchise_df.loc[nba_franchise_df.index >= 9,'Average NBA Franchise Value (USD Millions)'].round(2)

nba_franchise_df

    Year  Average NBA Franchise Value (USD Millions)
0   2023                                        3.80
1   2022                                        2.90
2   2021                                        2.50
3   2020                                        2.10
4   2019                                        1.90
5   2018                                        1.70
6   2017                                        1.40
7   2016                                        1.20
8   2015                                        1.10
9   2014                                        0.63
10  2013                                        0.51
11  2012                                        0.39
12  2011                                        0.37
13  2010                                        0.37
14  2009                                        0.38
15  2008                                        0.37
16  2007                                        0.35
17  2006                                        0.33
18  2005                                        0.30
19  2004                                        0.26
20  2003                                        0.25
21  2002                                        0.22
22  2001                                        0.21

In [17]:
# Rename francshise column to billions format to match previously clean DF's
nba_franchise_df = nba_franchise_df.rename(columns={'Average NBA Franchise Value (USD Millions)':'Avg NBA Franchise Value (USD billions)' })

# Review DF info after cleaning
print(nba_franchise_df.info())
nba_franchise_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Year                                    23 non-null     int64
 1   Avg NBA Franchise Value (USD billions)  23 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 496.0 bytes
None

    Year  Avg NBA Franchise Value (USD billions)
0   2023                                    3.80
1   2022                                    2.90
2   2021                                    2.50
3   2020                                    2.10
4   2019                                    1.90
5   2018                                    1.70
6   2017                                    1.40
7   2016                                    1.20
8   2015                                    1.10
9   2014                                    0.63
10  2013                                    0.51
11  2012                                    0.39
12  2011                                    0.37
13  2010                                    0.37
14  2009                                    0.38
15  2008                                    0.37
16  2007                                    0.35
17  2006                                    0.33
18  2005                                    0.30
19  2004                                    0.26
20  2003                                    0.25
21  2002                                    0.22
22  2001                                    0.21

## NBA Revenue Data

In [20]:
# Read in NBA revenue data and create DataFrame
nba_rev_path = '../data/raw/MVP2/nba_revenue.csv'
nba_rev_data = pd.read_csv(nba_rev_path)

# Create DataFrame
nba_rev_df = pd.DataFrame(nba_rev_data)
nba_rev_df

     Year NBA Sponsorship Revenue (USD Millions)
0   22/23                                  1,660
1   21/22                                  1,600
2   20/21                                  1,460
3   19/20                                  1,390
4   18/19                                  1,298
5   17/18                                  1,120
6   16/17                                    861
7   15/16                                    799
8   14/15                                    739
9   13/14                                    679
10  12/13                                    642
11  11/12                                    610
12  10/11                                    572
13  09/10                                    536

In [21]:
# Review info behind DataFrame
nba_rev_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Year                                    14 non-null     object
 1   NBA Sponsorship Revenue (USD Millions)  14 non-null     object
dtypes: object(2)
memory usage: 352.0+ bytes

**Cleaning Notes**
- Year will likely need to be reformatted from YY/YY --> YYYY to create universal Year column for joining
- Rev column: commas to period and period added from 2016-2009
- Change value to billions

In [22]:
# Replace commas with period (decimals)
nba_rev_df['NBA Sponsorship Revenue (USD Millions)'] = nba_rev_df['NBA Sponsorship Revenue (USD Millions)'].str.replace(',', '.')

# Check 
nba_rev_df

     Year NBA Sponsorship Revenue (USD Millions)
0   22/23                                  1.660
1   21/22                                  1.600
2   20/21                                  1.460
3   19/20                                  1.390
4   18/19                                  1.298
5   17/18                                  1.120
6   16/17                                    861
7   15/16                                    799
8   14/15                                    739
9   13/14                                    679
10  12/13                                    642
11  11/12                                    610
12  10/11                                    572
13  09/10                                    536

In [23]:
# Add decimal point (period since type is still 'object') to indexes <= 6
# Matching previous format nba_franchise_df.loc[nba_franchise_df.index >= 9, 'Average NBA Franchise Value (USD Millions)']
nba_rev_df.loc[nba_rev_df.index >= 6, 'NBA Sponsorship Revenue (USD Millions)'] =nba_rev_df.loc[nba_rev_df.index >= 6, 'NBA Sponsorship Revenue (USD Millions)'].apply(lambda x: '.' + x)

# Review efficacy
nba_rev_df

     Year NBA Sponsorship Revenue (USD Millions)
0   22/23                                  1.660
1   21/22                                  1.600
2   20/21                                  1.460
3   19/20                                  1.390
4   18/19                                  1.298
5   17/18                                  1.120
6   16/17                                   .861
7   15/16                                   .799
8   14/15                                   .739
9   13/14                                   .679
10  12/13                                   .642
11  11/12                                   .610
12  10/11                                   .572
13  09/10                                   .536

In [24]:
# Round revenue column to 2 decimal places
nba_rev_df['NBA Sponsorship Revenue (USD Millions)'] = nba_rev_df['NBA Sponsorship Revenue (USD Millions)'].astype('float64').round(2)

# Check data type conversion & rounding in DF
nba_rev_df.info()
nba_rev_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Year                                    14 non-null     object
 1   NBA Sponsorship Revenue (USD Millions)  14 non-null     float64
dtypes: float64(1), object(1)
memory usage: 352.0+ bytes

     Year  NBA Sponsorship Revenue (USD Millions)
0   22/23                                    1.66
1   21/22                                    1.60
2   20/21                                    1.46
3   19/20                                    1.39
4   18/19                                    1.30
5   17/18                                    1.12
6   16/17                                    0.86
7   15/16                                    0.80
8   14/15                                    0.74
9   13/14                                    0.68
10  12/13                                    0.64
11  11/12                                    0.61
12  10/11                                    0.57
13  09/10                                    0.54

In [26]:
# Change Column name
nba_rev_df = nba_rev_df.rename(columns={'NBA Sponsorship Revenue (USD Millions)':'NBA Sponsorship Revenue (USD Billions)'})

nba_rev_df.head(2)

    Year  NBA Sponsorship Revenue (USD Billions)
0  22/23                                    1.66
1  21/22                                    1.60